name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to GitHub workspace
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        continue-on-error: false
        env:
          CI_PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
        run: |
            # Commitlint
            npx --version
            npm install --location=global --save-dev @commitlint/config-conventional
            echo "module.exports = {
                extends: ['@commitlint/config-conventional'],
                rules: {
                    'header-max-length': [2, 'always', 100]
                }
            }" >commitlint.config.js
            npx commitlint --to HEAD --verbose
            echo "$CI_PULL_REQUEST_TITLE" | npx commitlint
        
            # Functional Tests
            composer install --prefer-dist
            ./vendor/bin/phpunit